### ISSUE TITLE
The elb often loss backend server

### ISSUE THREAD

**Issue by vipcxj** [kubernetes-sigs/cloud-provider-huaweicloud#225]
**What happened**:
At the beginning, the load balancing still worked normally. However, after a period of time, I found in Huawei cloud console that the back-end server of elb was missing, but my pod and service in k8s were working normally, which caused elb to fail to work

**What you expected to happen**:
The elb should works

**How to reproduce it (as minimally and precisely as possible)**:
I don't kown how to reproduce it. but it happen many times.
I need a solution to trace it ( for example logs )

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.4", GitCommit:"fa3d7990104d7c1f16943a67f11b154b71f6a132", GitTreeState:"clean", BuildDate:"2023-07-19T12:14:49Z", GoVersion:"go1.20.6", Compiler:"gc", Pl
atform:"linux/amd64"}
- Cloud provider or hardware configuration:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx-1693240433-controller
  namespace: ingress-nginx
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress-nginx-1693240433
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
    app.kubernetes.io/version: 1.8.1
    helm.sh/chart: ingress-nginx-4.7.1
  annotations:
    kubernetes.io/elb.class: shared
    kubernetes.io/elb.health-check-flag: 'on'
    kubernetes.io/elb.health-check-option: '{"delay": 3, "timeout": 15, "max_retries": 3}'
    kubernetes.io/elb.id: XXXXXXXX
    kubernetes.io/elb.lb-algorithm: LEAST_CONNECTIONS
    meta.helm.sh/release-name: ingress-nginx-1693240433
    meta.helm.sh/release-namespace: ingress-nginx
status:
  loadBalancer:
    ingress:
      - ip: 192.168.0.247
spec:
  ports:
    - name: http
      protocol: TCP
      appProtocol: http
      port: 80
      targetPort: http
      nodePort: 31825
    - name: https
      protocol: TCP
      appProtocol: https
      port: 443
      targetPort: https
      nodePort: 32684
  selector:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress-nginx-1693240433
    app.kubernetes.io/name: ingress-nginx
  clusterIP: 10.233.8.69
  clusterIPs:
    - 10.233.8.69
  type: LoadBalancer
  sessionAffinity: None
  externalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  allocateLoadBalancerNodePorts: true
  internalTrafficPolicy: Cluster
```
- OS (e.g: `cat /etc/os-release`):
PRETTY_NAME="Ubuntu 22.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.2 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

- Kernel (e.g. `uname -a`):
Linux node1 5.15.0-76-generic #83-Ubuntu SMP Thu Jun 15 19:16:32 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Network plugin and version (if this is a network-related bug):
calico v3.25.1
- Others:
